DROP TABLE IF EXISTS Pobyt;
DROP TABLE IF EXISTS Pracownik;
DROP TABLE IF EXISTS GoscHotelowy;
DROP TABLE IF EXISTS ZamowienieUslugi;
DROP TABLE IF EXISTS KartaHotelowa;
DROP TABLE IF EXISTS CennikUslugi;
DROP TABLE IF EXISTS Usluga;
DROP TABLE IF EXISTS OpcjaPobytu;
DROP TABLE IF EXISTS Hotel;


CREATE TABLE GoscHotelowy (
	PESEL UNIQUEIDENTIFIER PRIMARY KEY,
	Imie varchar(20) NOT NULL,
	Nazwisko varchar(20) NOT NULL,
	KrajPochodzenia varchar(20) NOT NULL,
	DataUrodzenia DATE NOT NULL,
);

CREATE TABLE Hotel (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	Adres varchar(50) NOT NULL,
	Nazwa varchar(40) NOT NULL,
);

CREATE TABLE OpcjaPobytu (
	Typ varchar(20) PRIMARY KEY,
);

CREATE TABLE Usluga (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	Typ varchar(20) NOT NULL,
	Nazwa varchar(100),
	Hotel UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Hotel(ID) NOT NULL
);

CREATE TABLE CennikUslugi (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	Cena DECIMAL(6, 2),
	DataRozpoczecia DATE NOT NULL,
	DataZakonczenia DATE,
	OpcjaPobytu varchar(20) FOREIGN KEY REFERENCES OpcjaPobytu(Typ) NOT NULL,
	Usluga UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usluga(ID) NOT NULL,
);

CREATE TABLE KartaHotelowa (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	DataWydania DATE NOT NULL,
	DataZwrotu DATE NOT NULL,
	OpcjaPobytu varchar(20) FOREIGN KEY REFERENCES OpcjaPobytu(Typ) NOT NULL,
	Hotel UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Hotel(ID) NOT NULL,
);

CREATE TABLE Pobyt (
	GoscHotelowy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES GoscHotelowy(PESEL),
	KartaHotelowa UNIQUEIDENTIFIER FOREIGN KEY REFERENCES KartaHotelowa(ID),
	PRIMARY KEY(GoscHotelowy, KartaHotelowa)
);

CREATE TABLE ZamowienieUslugi (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	KartaHotelowa UNIQUEIDENTIFIER FOREIGN KEY REFERENCES KartaHotelowa(ID),
	CennikUslugi UNIQUEIDENTIFIER FOREIGN KEY REFERENCES CennikUslugi(ID),
	DataRozpoczecia DATE,
	DataZakonczenia DATE,
	Oplacone BIT NOT NULL,
);
